tomcat-sdi:
  container_name: tomcat-sdi
  build: build
  environment:
  - MAXMEM=4096m
  - GEOSERVER_DATA_DIR=/var/geoserver_data
  - GEONETWORK_DATA_DIR=/var/geonetwork_data
  volumes:
  - ./webapps:/usr/local/tomcat/webapps
  - ./geoserver_data:/var/geoserver_data
  - ./geonetwork_data:/var/geonetwork_data
  - ./build/setenv.sh:/usr/local/tomcat/bin/setenv.sh
  ports:
  - "8078:8080"
  restart: unless-stopped
